### ISSUE TITLE
Implement Call Number (`Resource`) and Box Number (`Container`) form validation for AbsoluteIDs

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/lib_jobs#102]
I attempted to prototype this within https://github.com/pulibrary/lib_jobs/tree/absolute-ids, however, this is currently disabled given that I encountered performance issues within the staging environment.

**Comment by jrgriffiniii** [comment]
This was originally implemented using `ResourceController#search` and `ContainerController#search` actions, which received `POST` requests submitted using the `fetch` API.

**Comment by tpendragon** [comment]
This is...server side validation that the numbers aren't already taken?

**Comment by jrgriffiniii** [comment]
Sorry, yes, this is for validation addressing the following conditions:

- The Call Number exists in ArchivesSpace as a `Resource`
- The Container Number exists (as an index for the `TopContainer` member of the `Resource`, or a node within the `Resource`/`ArchivalObject` hierarchy tree
- The barcode being applied to the `TopContainer` is not already in use (the ArchivesSpace REST API raises an error if this is the case)
