### ISSUE TITLE
Map OIT Patron Data to Alma SIS XML Format

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lib_jobs#127]
Looks like per https://developers.exlibrisgroup.com/alma/integrations/user-management/sis/synch/ we have to submit our data as XML, each individual user will take the form document here: https://developers.exlibrisgroup.com/alma/apis/docs/xsd/rest_user.xsd/?tags=GET. 

Many of the elements that can be supplied are optional. A first pass at mapping the elements from the OIT feed to the Alma User Object:

https://docs.google.com/spreadsheets/d/12MjegjI9mjwAP9E6nA06bPCo5qD-e5LyMJnc1bDVdiE/edit#gid=0

**Comment by carolyncole** [comment]
fixed by https://github.com/pulibrary/lib_jobs/commit/a9f1b575c821ae9dc8bde9624173ff34142fae25
