### ISSUE TITLE
Update Address Mappings for Patron Type GRAD

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lib_jobs#200]
When managing addresses for the patron type grad the "CAMPUS" address fields should be mapped into the address type of "Work". At the moment it appears we aren't loading this address. After a review with circ staff this is useful information in part because it tells them which department the graduate student is a part of.

**Comment by carolyncole** [comment]
@kevinreiss Should Grad students get a CAMPUS address in addition to the permanent and dorm? Or should they be treated like a faculty staff? https://github.com/pulibrary/lib_jobs/blob/main/app/models/alma_people/alma_xml_person.rb#L65-L68

**Comment by kevinreiss** [comment]
Mark and I talked a bit about this and we think they should be treated like faculty staff.
