### ISSUE TITLE
Validate the transaction numbers in the peoplesoft Fund adjustment

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/lib_jobs#211]
When the file is retrieved from people soft we need to validate that no duplicates transaction ids have been sent from the system in the past.

Send an email to Mark, Kevin, Carolyn and do not transfer the file to Alma.  Put the file in an error directory.

**Comment by carolyncole** [comment]
@mzelesky What do we want to do about invalid invoices?  Should I only mark off the valid ones, since we are expecting the invalid ones to be sent again at a later date?

**Comment by mzelesky** [comment]
This is not for the voucher feed, but the fund transactions.

**Comment by mzelesky** [comment]
There is no need to track invoice ids and look for duplicate invoices. This ticket is for the files posted to lbvchr-p/fund_adjustment

**Comment by carolyncole** [comment]
@mzelesky Ok, at this point we are not even reading that file in, we are just transferring it to the ftp location.  That will take little more time to do.  I'll see what I can do today.
