### ISSUE TITLE
Modify Staff List Job to Utilize only Peoplesoft Data

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lib_jobs#215]
End use of local staff database for content put into this feed. Fields that don't have a value that can be mapped from peoplesoft should be removed from the feed.

**Comment by kevinreiss** [comment]
Close when https://github.com/pulibrary/lib_jobs/pull/241 is merged.

**Comment by kevinreiss** [comment]
Do issue #389 in lib_jobs before moving forward with the open PR from @carolyncole

**Comment by kevinreiss** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DACS-Maintenance-5da0db919c4ddf0001b2eb92/issues/pulibrary/lib_jobs/215?planning-poker) with Zenhub @christinach @maxkadel @regineheberlein @rladdusaw @sandbergja

**Comment by kevinreiss** [comment]
Make sure to test the scenario to prefer the "Register Title" field when it's present in the CSV report from the data warehouse.

**Comment by sandbergja** [comment]
closed by #389
