### ISSUE TITLE
Request Additional Title Data from Peoplesoft

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lib_jobs#216]
We need to request some additional title fields be added to the "Department Absence Manager" report that we currently use to build the staff list. A blocking issue to completing #215.

**Comment by kevinreiss** [comment]
Need to ask via SN@P for possible title related fields from the warehouse.

**Comment by kevinreiss** [comment]
We only receive the generic "title" field now which is functional job title, so all librarians have the title of "Librarian". We need get a more descriptive title related to job function added to the report we recieve. This data is available in LDAP.

**Comment by carolyncole** [comment]
Sent an email to Monica M. and she replied

**Comment by carolyncole** [comment]
We are going to get an updated file tomorrow. 🤞 this does not break the current code.

**Comment by kevinreiss** [comment]
We do have the "Register Title" field in the report. That's what we need to prefer when available. #389 will implement this. Closing.
