### ISSUE TITLE
Change the algorithm for voucher id to be definitely unique

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/lib_jobs#221]
We should verify that it can include letters.  If it can include numbers convert it to HEXidecimal to make it shorter instead of just truncating fro 2..8.

convert part character 2 through `06421` at the end.

`id[2..-6].to_i.to_s(32)` pad with zeros if it is not 7 characters long

https://github.com/pulibrary/lib_jobs/blob/main/app/models/peoplesoft_voucher/alma_xml_invoice.rb#L19

**Comment by mzelesky** [comment]
Confirmed that voucher IDs can include letters beyond the first character of the voucher ID (which is always 'A'). But we need to upcase the ID.
