### ISSUE TITLE
Create Alma Patron XML to Add NET ID data to Accounts missing this identifier

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lib_jobs#224]
Leverage https://github.com/pulibrary/lib_jobs/blob/main/app/models/alma_people/alma_person_feed.rb to create a task that can produce the ALMA patron XML feed format from a CSV of data points that move the net ID value currently stored in the Alma user title field to the netID value in the identiers section of the alma patron field. The match key will remain nine-digit primary ID.

**Comment by carolyncole** [comment]
Move the title field to the netid field.

https://docs.google.com/spreadsheets/d/1cJUCTdGqEOMuYOPSb_x6GFkUXRpUKo6DHQi9uzD3ILM/edit#gid=163688218

**Comment by kevinreiss** [comment]
We could test and see if the importer would accept the minimal XML we need to make this update

```<user link="string">
  <primary_id>10101101</primary_id>
  <status>ACTIVE</status>
  <user_title></user_title>
  <user_identifiers>
    <user_identifier segment_type="External">
      <id_type>netID</id_type>
      <value>mynetid</value>
      <note></note>
      <status></status>
    </user_identifier>
  </user_identifiers>
</user>```

**Comment by kevinreiss** [comment]
From the input spreadsheet the title_to_netid field can go in as the netID identifier.

**Comment by kevinreiss** [comment]
@mzelesky I believe this isn't really an issue any longer. Closing this. Re-open if you think we need to discuss further.
