### ISSUE TITLE
XML structure changed in PeopleSoft voucher status job

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/lib_jobs#232]
The XML schema has changed for the PeopleSoft voucher status files.

Now, instead of PYMNT_AMT for the voucher total, it is PAID_AMT. So we will have to adjust the model:

https://github.com/pulibrary/lib_jobs/blob/5c261a16e68f06710cf2449e219951964b398c8d/app/models/alma_invoice_status/status_query.rb#L27

That should be
` payment_amount: safe_lookup(row, 'PAID_AMT'),`

**Comment by carolyncole** [comment]
fixed by #233
