### ISSUE TITLE
Overlapping Electonic collections perm vs subscription

### ISSUE THREAD

**Issue by pdiskin** [pulibrary/lib_jobs#242]
Working with Kevin C.  He brought up some points:
Issues:
1. 599 being deleted from the merge.  
2. 599 should be somewhere in the portfolio for the permanent acq. 
3. User restrictions should also go in the portfolio.  Do we want this to display in Black light?  The public note maybe used for this.  

Larger question for invoicing:
Bibid was in voyager, but in Alma the Portfolio ID should be used.

**Comment by kevinreiss** [comment]
@pdiskin think that this was intended for alma-config. Do we need to re-create it there at this point?
