### ISSUE TITLE
PeopleSoft staff-directory report: student employees?

### ISSUE THREAD

**Issue by pmgreen** [pulibrary/lib_jobs#244]
We currently have well over 100 student employees with assigned roles in Alma with no definitive way to audit them beyond manually constructed spreadsheets. Is it possible to get student employee data from PeopleSoft to include in the staff-directory report? Who can we ask about this?

**Comment by kevinreiss** [comment]
It's a question for the data warehouse maintainers to see if it is actually possible to get a list of students who are actively employed by a department.

**Comment by kevinreiss** [comment]
I think it would be a separate report from the existing one.

**Comment by kevinreiss** [comment]
@pmgreen I don't think we can really get a report like this easily. We'd need to talk to with the data warehouse maintainers. Do you think the auto-expiration workflow for these that we've added is sufficient?
