### ISSUE TITLE
Manual Multi match handling required for unknown matching

### ISSUE THREAD

**Issue by pdiskin** [pulibrary/lib_jobs#245]
Manual Multi match handling required for import profiles using match method 024/035 that have a "single match match only with the same inventory type" checked, 
Electronic records required us to choose between a physical record with no match in the 024(did not exist) and the 035 which was completely different and the correct electronic record which had valid  match points.

**Comment by kevinreiss** [comment]
Believe this is for alma-config. Closing. @pdiskin re-open this elsewhere if needed.
