### ISSUE TITLE
spine-o-matic configuration file adjustment

### ISSUE THREAD

**Issue by pmgreen** [pulibrary/lib_jobs#251]
Issues to resolve:
- how to remove the Oversize from call numbers
- how to handle NO CIRC locations and Reference locations that print Ref. on top of the location symbol.

The current configuration file: https://library.princeton.edu/sites/default/files/aboveLabel.txt

**Comment by pmgreen** [comment]
Asked MWC and Jamie about this

**Comment by kevinreiss** [comment]
@pmgreen is there any code in this repo about the spine label? I don't think so. I will close this, but we could consider creating a distinct github repo for our recommended spine label config.

**Comment by pmgreen** [comment]
@kevinreiss no code, just the config file. 
We do have some documentation on Confluence: https://lib-confluence.princeton.edu/display/ALMA/Spine+Labels
