### ISSUE TITLE
Implement New Bursar Workflow

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lib_jobs#254]
In consultation with circulation staff. High level workflow:

1. Tell student the fine is going to the bursar.
2. Create new bursar fine on the student's account in Alma.
3. 2 days later, student returns book.
4. Waive bursar fine.
5. File gets sent on Sunday, with no info at all about that fine.

**Comment by mzelesky** [comment]
See https://gist.github.com/mzelesky/553f18eee1f2779d8cb319bc23eb3453 for code that transforms Alma output to the PeopleSoft output.

**Comment by mzelesky** [comment]
The code needs a complete re-write from top to bottom, unfortunately. The end result will be much simpler code though.

**Comment by kevinreiss** [comment]
@mzelesky I will close this and open a new issue for the "simpler" process since I know it's very different from the multi-step  work outline here.

**Comment by mzelesky** [comment]
The new approach is a hybrid approach.

For library credits, we will rely on the existing framework, where fine fee transactions with the fine/fee type of Credit will be exported via the Bursar transfer job in Alma.

For payment of library fines, the following process must be followed:
1. Circulation staff pay the fine with the payment method of 'Bursar Transfer'.
2. An Analytics report will run once a week to capture fine payments.
3. The output of the Analytics report will need to be translated into the format required for the bursar office.

**Comment by mzelesky** [comment]
Re-opening, as the new approach is a hybrid approach that will use the code written before.

**Comment by mzelesky** [comment]
See https://gist.github.com/mzelesky/79a51cfc5f7d83bd6e49581cfd33d37a for processing payments from Analytics.

**Comment by mzelesky** [comment]
Files are going to be posted from Alma into the /alma/bursar directory every Monday at 3 AM EST for payments.

Credits are going to be posted from Alma into that directory every Sunday at 9 PM EST. Credits will rely on the Bursar export job.

Ideally, the payment job would run Tuesday mornings at 10:30 AM EST, while the credit job would run Thursday mornings at 11:30 AM EST.

The files are processed manually by staff in campus finance, hence the need for the jobs to be run on different days. The filename for the output has to be the same for both integrations.

**Comment by kevinreiss** [comment]
I think we are done with this, correct @mzelesky. Re-open if I'm wrong.
