### ISSUE TITLE
Implementing Workflow to submit data to the POD Project

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lib_jobs#273]
Background Docs/Starting Places

* Havard Publishing Profile: https://wiki.harvard.edu/confluence/pages/viewpage.action?pageId=248588371
* Test code: https://github.com/pulibrary/pod_scripts
* Project Site https://pod.stanford.edu 

- [x] #277
- [x] #278
- [x] #281
- [x] #280
- [x] #279
- [x] #294

**Comment by carolyncole** [comment]
Publishing job will exclude any records that are electronic resources.

**Comment by kevinreiss** [comment]
Sample set of initial records are on lib-sftp in the the /alma/pod directory.

**Comment by kevinreiss** [comment]
Companion config issue: https://github.com/PrincetonUniversityLibrary/alma-config/issues/187
