### ISSUE TITLE
Set up a job to submit a feed of deletes to POD. 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lib_jobs#279]
Goal: report deletes once a day.

**Comment by sandbergja** [comment]
Alma is already providing the 'd' in position 05 of the leader, so we may be able to use the same process as adds/updates.

**Comment by kevinreiss** [comment]
Per the POD docs it seems this would be acceptable so we can probably just move forward with Alma's output after getting the XML namespaces in order.

**Comment by sandbergja** [comment]
closed by #287
