### ISSUE TITLE
Configure Summon to use LibKey

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lib_jobs#306]
Follow instructions here: https://thirdiron.atlassian.net/wiki/spaces/BrowZineAPIDocs/pages/104988678/Ex+Libris+Summon+Overview+and+Step-by-Step+Installation+Guide. 

This was requested by Joe M.

**Comment by kevinreiss** [comment]
@pmgreen did we actually do this?

**Comment by pmgreen** [comment]
@kevinreiss yes, under INC0242329
