### ISSUE TITLE
SCSB renewal due date not being calculated correctly

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/lib_jobs#324]
Items for faculty and grad students (where the due date is June 15th of the next year) are being calculated as June 14th at 11:59 PM. I am wondering if this is due to the time-zone difference (June 15th at midnight in UTC is June 14th in EST). Is this due to what I think it is, or is there some other thing at play?

**Comment by maxkadel** [comment]
@mzelesky  If the due date is June 15th of next year, what time should the item be due? June 15, 2023, 11:59 pm EST?
