### ISSUE TITLE
Alma Renew Job is no longer running.

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/lib_jobs#326]
https://lib-jobs.princeton.edu/data_sets?utf8=%E2%9C%93&category=AlmaRenew&commit=Filter

**Comment by carolyncole** [comment]
Here is the error from the log

**Comment by mzelesky** [comment]
If the expiration date of the user is blank, or the primary identifier is 'None', the line should be skipped. I have revised the query to eliminate these lines as well. Hopefully that will mean no more lines with empty values should be returned.

**Comment by christinach** [comment]
@mzelesky I'm handling the error in https://github.com/pulibrary/lib_jobs/pull/330. 
When you say lines with empty values do you mean that we shouldn't have at all `<ns1:DesiredDateDue />\n` if there is no value?

**Comment by christinach** [comment]
@mzelesky is primary identifier the user identifier? If yes, why would it be "None" ?

**Comment by christinach** [comment]
I merged https://github.com/pulibrary/lib_jobs/pull/330 and deployed to production the error handling PR. We ran the job with @kevinreiss and:
1. We are seeing barcodes in the processed CSV files in lib-sftp that do not exist in Alma
2. Barcode exists in SCSB but they are not loaned (green check icon) '33433122986742'. This Barcode was refilled to RECAP today (@kevinreiss checked the requests)

https://lib-jobs.princeton.edu/data_sets/2656 -> Data: 

We tried to send renewals for 1447 items. 59 errors were encountered. Unknown Item (33433002428260) AlmaRenewItemService failed () Unknown Item (33433002428260) Unknown Item (33433002428260) Unknown Item (33433017525563) Unknown Item (33433057083457) AlmaRenewItemService failed () AlmaRenewItemService failed () Unknown Item (33433122986742) AlmaRenewItemService failed () Unknown Item (AR72712074) AlmaRenewItemService failed () Unknown Item (33433002428260) Unknown Item (32044111335147) Unknown Item (32044127175040) AlmaRenewItemService failed () AlmaRenewItemService failed () AlmaRenewItemService failed () Unknown Item (33433002428260) Unknown Item (33433002428260) AlmaRenewItemService failed () AlmaRenewItemService failed () AlmaRenewItemService failed () AlmaRenewItemService failed () AlmaRenewItemService failed () AlmaRenewItemService failed () Unknown Item (CU70054428) Unknown Item (CU70054428) AlmaRenewItemService failed () AlmaRenewItemService failed () AlmaRenewItemService failed () AlmaRenewItemService failed () AlmaRenewItemService failed () AlmaRenewItemService failed () AlmaRenewItemService failed () AlmaRenewItemService failed () AlmaRenewItemService failed () Unknown Item (33433002428260) Unknown Item (33433002428260) AlmaRenewItemService failed () AlmaRenewItemService failed () Unknown Item (33433017525563) Unknown Item (33433057083457) AlmaRenewItemService failed () AlmaRenewItemService failed () AlmaRenewItemService failed () Unknown Item (33433122986742) AlmaRenewItemService failed () AlmaRenewItemService failed () AlmaRenewItemService failed () AlmaRenewItemService failed () AlmaRenewItemService failed () AlmaRenewItemService failed () AlmaRenewItemService failed () AlmaRenewItemService failed () AlmaRenewItemService failed () AlmaRenewItemService failed () AlmaRenewItemService failed () Unknown Item (33433002428260)

**Comment by christinach** [comment]
Barcode: `33433016615068` : 
We checked in alma and has no `due date` even though the due date exists in the file. It appears in two files: scsb_renewal_export_202205190612.csv.processed and scsb_renewal_export_202205200612.csv.processed

**Comment by christinach** [comment]
@mzelesky can we review these files tomorrow?

**Comment by christinach** [comment]
per @mzelesky We are seeing barcodes in the processed CSV files in lib-sftp that do not exist in Alma -> if the file is refilled in SCSB then it is not in Alma anymore. This job is one day behind so this is always a possibility.

**Comment by christinach** [comment]
> Barcode: `33433016615068` : We checked in alma and has no `due date` even though the due date exists in the file. It appears in two files: scsb_renewal_export_202205190612.csv.processed and scsb_renewal_export_202205200612.csv.processed

We checked in ALma and the Process type for this barcode is 'In transit'. This is why there is no due date.
