### ISSUE TITLE
Don't send an ncip renewal when the primary identifier is 'None' or the expiration date is nil 

### ISSUE THREAD

**Issue by christinach** [pulibrary/lib_jobs#335]
@mzelesky is handling this in his query in the Alma side; However we want to update the code so that 
we dont send an ncip renewal when the primary identifier is 'None' or the expiration date is nil. Also update: https://github.com/pulibrary/lib_jobs/blob/2c43195198deeec9092bee62ad4812b8d46a6aac/app/models/alma_renew/item.rb#L24 which was added to handle the initial argument error.

**Comment by carolyncole** [comment]
There are 2000 users that have no expiration, due to the patron feed.

**Comment by maxkadel** [comment]
I think the expiration date in this context is for when the item is no longer wanted, not the patron's expiration date.

**Comment by maxkadel** [comment]
We will discuss how to test this with Mark Zelesky when he gets back from vacation

**Comment by mzelesky** [comment]
This is actually referring to the patron's expiration date.
