### ISSUE TITLE
More descriptive output - Include an identifier in the alma renewal job log

### ISSUE THREAD

**Issue by christinach** [pulibrary/lib_jobs#336]
Looked into this because of https://lib-jobs.princeton.edu/data_sets/2665
`We tried to send renewals for 193 items. 1 errors were encountered. Unknown Item (33433002428260)`
```
Data file
Category
AlmaRenew
Status
true
[Edit](https://lib-jobs.princeton.edu/data_sets/2665/edit) | [Back](https://lib-jobs.princeton.edu/data_sets)
Tasks: TOP => lib_jobs:renew_alma_requests
(See full trace by running task with --trace)
output error : string is not in UTF-8
output error : invalid character value
output error : invalid character value
output error : invalid character value
output error : string is not in UTF-8
output error : string is not in UTF-8
output error : string is not in UTF-8
output error : string is not in UTF-8
output error : invalid character value

**Comment by maxkadel** [comment]
Need more details about what more descriptive output should include - @mzelesky

**Comment by mzelesky** [comment]
I think knowing which items were renewed instead of a tally would be useful, with each item listing if it was successfully renewed or not.

**Comment by maxkadel** [comment]
@mzelesky  - so include the successful items as well? All those "Unknown Item (33433002428260)" things mean that the item with barcode 33433002428260 was not renewed because it was an "Unknown Item" according to Alma. If that's all that's needed, maybe we can improve the wording to make that clearer?

**Comment by kevinreiss** [comment]
@mzelesky just another ping on this one so we can flesh out the details here.
