### ISSUE TITLE
Document NCIP - renewal job

### ISSUE THREAD

**Issue by christinach** [pulibrary/lib_jobs#338]
As a start include in `docs/renewal_job.md` information about NCIP and way to troubleshoot errors. 

https://developers.exlibrisgroup.com/alma/integrations/resource_sharing/broker/ncip/application_profile/v2/

https://developers.exlibrisgroup.com/wp-content/uploads/alma/xml_json_samples/RenewItem.xml

**Comment by maxkadel** [comment]
This was done on PR https://github.com/pulibrary/lib_jobs/pull/364
