### ISSUE TITLE
Some invoice IDs in the Payment Status integration contain junk

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/lib_jobs#351]
Some invoice IDs look like this:

`<INVOICE_ID><![CDATA[17268164430006421
4/15/22 AS - attached a copy of returned check
https://princeton.service-now.com/now/workspace/agent/record/sc_task/e993fe02872f4110731f322d0ebb353e]]></INVOICE_ID>`

Anything after the final number in the INVOICE_ID field should be scrubbed. This is junk data introduced by the campus finance team as they work through issues. They have been told not to put notes in the field, but sometimes mistakes happen.

this should be removed ` 4/15/22 AS - attached a copy of returned check https://princeton.service-now.com/now/workspace/agent/record/sc_task/e993fe02872f4110731f322d0ebb353e`

**Comment by christinach** [comment]
@mzelesky says this is urgent because it prevents the integration from working in Alma.
