### ISSUE TITLE
Person feed should check for a blank expiration date coming from Peoplesoft

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/lib_jobs#355]
We can not default this.  We should just skip the update.

An error message email should be sent to PUL stakeholders if there is a nil expiration date.  The email should have a list of the patrons with a nil date.

**Comment by sandbergja** [comment]
@mzelesky when you're available, I have two questions:

1. Which PUL stakeholders should receive these emails?
2. What information about the person should be included in the emails?  My current PR just includes their NetID, but we could include other info, too.

**Comment by sandbergja** [comment]
Per @kevinreiss, these emails should also include the employee id (EMPLID)
