### ISSUE TITLE
Add a feature flipper for the voucher feed

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/lib_jobs#371]
Per @mzelesky, we should turn off the voucher feed job each year between the invoice cut-off and the first day invoices can be approved in the new fiscal year "In case someone mistakenly logs in and runs the invoice export job from Alma after the invoice cut-off"

This year, we did a [PR to turn it off](https://github.com/pulibrary/lib_jobs/pull/369) and a [PR to turn it back on](https://github.com/pulibrary/lib_jobs/pull/370).  Perhaps a feature flipper would be a better solution.

- [x] Add FlipFlop Gem
- [x] Add user list to Princeton Ansible. List is DACS team plus Alma Tech Team (https://github.com/pulibrary/princeton_ansible/pull/3903)
- [x] Update lib-jobs to understand admin users: see https://github.com/pulibrary/orangelight/pull/3134
- [x] Wrap job up in Feature Flipper
- [x] When job is off return a null value and log the event. 
- [x] Demonstrate feature to Alma Tech Team 
- [ ] Remove the cookie column
- [ ] Add a link to /features for logged in users

**Comment by sandbergja** [comment]
Maybe we can investigate the flip flop gem: https://github.com/pulibrary/orangelight/issues/3126

**Comment by mzelesky** [comment]
The dates change every year, so I don't think the timing can be automated. But having a simple mechanism to turn on/off a job sounds like a great idea.

**Comment by kevinreiss** [comment]
Within the rake task, make it so when this job is "off" return a null action and log the result as "no action taken" or something to that effect.
