### ISSUE TITLE
Temp directory filling up disk

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/lib_jobs#385]
The `/tmp` directory is filling up on lib-jobs-prod1. We have asked Francis to increase the size of the disk, but we also need to clean up files once we no longer need them. 

Some options:
* A cron job to clean out /tmp - items older than X days?
* Change the code so that artifacts aren't kept in /tmp, but are made in ephemeral temp directories that are deleted when the block exits
* Have the final step of certain jobs be to clean up files
* pod_clean files do not seem to be compressed (at least not when they're persisted to /tmp) - should we compress them at some point?

**Comment by regineheberlein** [comment]
See https://app.honeybadger.io/projects/100710/faults/87627821/01GB7WCAHM0W5G7EY18RGJYENM?q=occurred.after%3A%227+days+ago%22#notice-summary
