### ISSUE TITLE
New work orders for EAL

### ISSUE THREAD

**Issue by cathyprinceton** [pulibrary/lib_jobs#388]
Two new work orders are needed for the EAL: "EAL Processing" and "EAL Marquand Processing" under the type AcqDepttechserv. Mark created the 2 work orders in Sandbox. Waiting for Lia to test and also to learn her feedback. Once that's done. Will move to production.

**Comment by kevinreiss** [comment]
Closing per convo with Mark and Cathy, ticket is for alma-config.
