### ISSUE TITLE
Prefer Register Title when Present in HR Report for Staff List Processing

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lib_jobs#389]
There are two "title" fields in the "Department Absence Manager Report - Library-en" that we process to create the daily staff report that is loaded into the website. The fields are "Title" and "Register Title". "Title" is always populated for a staff person, "Register Title" seems to be used for DOF and Admin staff. Right now we only look at the "Title" field when creating an HR person record: 

https://github.com/pulibrary/lib_jobs/blob/17db7285c3107452f2306fdcde82c48ed7cf7429/app/models/web_staff/staff_directory_generator.rb#L75

We need to add a method to see if the individual has the "Register Title" field populated and if it is, prefer that over the basic "Title" field.

**Comment by kevinreiss** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DACS-Maintenance-5da0db919c4ddf0001b2eb92/issues/pulibrary/lib_jobs/389?planning-poker) with Zenhub @rladdusaw @maxkadel @christinach @regineheberlein @sandbergja

**Comment by sandbergja** [comment]
This was fixed by #241 , but I'm going to open a PR that just adds a few unit tests as added confirmation.
