### ISSUE TITLE
Compress Data Submitted to POD

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lib_jobs#394]
The POD Project can accept compressed MarcXML files now. 

- [ ] We should re-factor to submit the xml we send in compressed form.

**Comment by kevinreiss** [comment]
After we make this change we should create a new stream in POD that we submit a full dump to that stream. When complete we will. make this new stream the default one in POD. Let the POD support list know pod-support@lists.stanford.edu when we decide to do that.

**Comment by kevinreiss** [comment]
https://github.com/pod4lib/aggregator/wiki/Streams-and-their-files

**Comment by maxkadel** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DACS-Rails-62754f60cf98a10014f28e1e/issues/pulibrary/lib_jobs/394?planning-poker) with Zenhub @leefaisonr @regineheberlein @rladdusaw @sandbergja

**Comment by kevinreiss** [comment]
I'm not sure if this question predates the creation of the princeton-test-set stream, but I think once we are confident we have a full set of our records in that stream we can work with the POD maintainers to make that stream our default one so the stream currently in production with uncompressed records can be removed.

**Comment by kevinreiss** [comment]
I will reach out to the POD and ask them how they want to coordinate switching the test stream to being our "production" stream.

**Comment by christinach** [comment]
We should run a full publishing for POD to populate the full record set.

**Comment by maxkadel** [comment]
Their system was having issues when they ran the normalization process, they will re-run over the weekend. Will check back in on Monday. May need to update our stream to send to new stream.

**Comment by kevinreiss** [comment]
New default is at https://pod.stanford.edu/organizations/princeton/streams/princeton-prod-0223. We can keep sending up to this stream and stop sending them to the other two streams which the POD folks will delete once we give them the ok.
