### ISSUE TITLE
Create LibCal Event Feed CSV

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lib_jobs#415]
Create a task that parse the non-standard libcal RSS feed (https://libcal.princeton.edu/rss.php?m=cat&iid=771&cid=12260&cat=50867) and produces a CSV file that contains the following columns. This CSV will be used to in place of the current ICS feed imported into the Drupal Website for events, see https://github.com/pulibrary/pul_library_drupal/issues/1944 for more background. The task should publish a CSV file to a static URL that a client could pull this data from at a regular interval (similar to the existing StaffDirectory task) 

Column mappings from the RSS feed to include:

GUID -> ```<guid>```
Title -> ```<title>```
Description -> ```<description>```
Date Start -> ```<libcal:date> - <libcal:start>``` (combine element values)
Date End -> ```<libcal:date> - <libcal:end>``` (combine element values)
Location -> ```<libcal:location>, <libcal:campus>``` (combine element values when both are present)
URL -> ```<link>```
Categories ->  ```<category>``` (multi-valued field, separate with a delimiter when more than one is present).

One mapping point to note. The existing calendar ICS feed GUIDs took the form "UID:LibCal-12260-9613672". 12260 is the calendar ID,  9613672 is the unique ID of the event/workshop in Libcal. The GUID element in the RSS feed is just the URL https://libcal.princeton.edu/event/9613672. If we want to avoid importing duplicate events we will need to make the GUID take this form otherwise we'll need to go through and delete duplicate events.

**Comment by christinach** [comment]
We might want to parse this from https://libcal.princeton.edu/ical_subscribe.php?cid=12260&k=79a5e62a54.

**Comment by sandbergja** [comment]
Maybe this gem would work for the ical/ics approach: https://github.com/icalendar/icalendar#parsing-icalendars

**Comment by kevinreiss** [comment]
```BEGIN:VEVENT
DTSTART:20230414T173000Z
DTEND:20230414T190000Z
DTSTAMP:20230414T000000Z
SUMMARY:This Sculpture Rocks!
DESCRIPTION:In this journey of sculptures\, Emily Wild (Chemistry\,
 Geosciences and Environmental Studies Librarian) will (1) give participants
 classroom instruction--an introduction to library research of the Princeton
 University Library geosciences collections and online USGS collections\;
 and (2) provide an outdoor walking tour of the stone and metal artwork
 around the Princeton University campus and in the Princeton\, NJ
 community.\n\nAdditional library research information will be provided for
 the geology (natural resources) and chemistry (metal and element
 properties) of sculptures in the Princeton University Art Museum\, Grounds
 for Sculpture\, Shelburn Museum\, and The Metropolitan Museum of Art
 collections.\n\nPrior to joining the Princeton University Library in 2018\,
 Emily worked for about 23 years as a USGS Hydrologist and USGS Librarian
 (Physical Scientist). Her experiences and interests with the intersection
 of geology and sculptures go back to the 1970s while growing up within her
 family of artists in Upstate New York. \n\nThe outdoor sculpture walking
 tour will be held\, rain or snow or shine. \n\nImage by E.Wild\, Summer
 2022 : Vita by Michael Shewmaker at Grounds for Sculpture
LOCATION:Lewis Library - Room 225\, Lewis Science Library
ORGANIZER;CN="Emily Wild":MAILTO:ewild@princeton.edu
CATEGORIES:Workshops
UID:LibCal-12260-9713468
URL:https://libcal.princeton.edu/calendar/events/This_Sculpture_Rocks
END:VEVENT

END:VCALENDAR%```

**Comment by kevinreiss** [comment]
example event data. ⏫
