### ISSUE TITLE
Upgrade to Ruby 3.1

### ISSUE THREAD

**Issue by christinach** [pulibrary/lib_jobs#429]
- [x]  Add current Ruby 3.1.x to CircleCI
- [x]  Fix any failing tests or dependency issues caused by upgrade to 3.1.x
- [x]  Make sure that aspace_helpers is compatible with ruby 3.1.x, since it is on the same box.
- [x]  Provision staging box to use Ruby 3.1.x
- [x]  Deploy code that works with 3.1.x to staging
- [x] Test on staging box with 3.1.x
- [x] Provision production box to use Ruby 3.1.x
- [x] Deploy to prod, confirm working on Ruby 3.1.x

**Comment by maxkadel** [comment]
Need to double check that cron jobs are still running after deploy (deployed 12/21/2022 at 12:20 pm est)

**Comment by christinach** [comment]
closed by https://github.com/pulibrary/lib_jobs/pull/433
