### ISSUE TITLE
NCIP Renewal for SCSB broken

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/lib_jobs#434]
### Expected behavior
Renewals for SCSB partner items submitted through their Library Card get renewed in Alma through an NCIP call.
### Actual behavior
~https://lib-jobs-staging.princeton.edu/ncip-renew returns a 404~ 
Partner items are not being renewed.

### Impact of this bug
Users are not able to renew SCSB partner materials, which can result in overdue fines and other patron issues. Joan and Marie have identified this as a major problem.

**Comment by mzelesky** [comment]
From the logs (see https://lib-jobs.princeton.edu/data_sets/5026), it looks like an attempt is being made to process the renewals, but the items aren't found. Perhaps code is pointing to the Alma sandbox?

It looks like I also need to update the URL in the partner parameters to be https://lib-jobs.princeton.edu/ncip-renew.

**Comment by maxkadel** [comment]
I believe it has been using https://princeton.alma.exlibrisgroup.com/view/NCIPServlet as the endpoint. 

I believe the response from the endpoint for each of the non-renewed items is just "Unknown Item". I've looked for the barcodes in Alma and they appear to be present as Location: "Borrowing Resource Sharing Requests" (see, e.g., barcode CU56955006; barcode 33433099769956)

**Comment by maxkadel** [comment]
Between the working and non-working runs of this rake task (12/4 - 12/5), the headers on the CSV built by Alma changed from `Barcode,Patron Group,Expiry Date,Primary Identifier` to `Barcode,Patron Group,Expiry Date,User Primary Identifier`, meaning that all the user_id's were not set.

**Comment by mzelesky** [comment]
I have updated the headers for the CSV, so we will see if that makes it work when this runs the next time. If it does, will it work if I manually modify all the files generated since 12/4 to fix the header and then remove `.processed` from each filename?

**Comment by maxkadel** [comment]
> I have updated the headers for the CSV, so we will see if that makes it work when this runs the next time. If it does, will it work if I manually modify all the files generated since 12/4 to fix the header and then remove `.processed` from each filename?

Yes, I believe if you modified those files to correct the header and remove the `.processed`, then they would be processed correctly the next time the rake task was run, either by the cron job, or by a developer.

**Comment by mzelesky** [comment]
Can we close this ticket? From my perspective, the issue is solved thanks to @maxkadel looking at the CSV headers of the file. Thank you again for your work on this!

**Comment by sandbergja** [comment]
@mzelesky I agree.  Closing, since the immediate issue was resolved, and #435 should guard against similar occurrences in the future.
