### ISSUE TITLE
Voucher ID not guaranteed to be unique.

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/lib_jobs#436]
### Expected behavior
Every voucher ID would be a unique 7-character hash derived from the unique invoice identifier.

### Actual behavior
One invoice was passed through the lib-job with the same voucher ID as a previous invoice. This was due to not knowing the structure of the Alma unique invoice identifier. I had assumed that the first 2 digits of the identifier could be ignored, but that is not true. In this case, the only 2 digits that were different between the 2 invoices were the first 2 digits.

I have a tentative solution (omitting the last 6 digits of the invoice identifier), but I am awaiting confirmation that the last 6 digits can safely be ignored.

### Steps to replicate
Run the method at https://github.com/pulibrary/lib_jobs/blob/main/app/models/peoplesoft_voucher/alma_xml_invoice.rb#L18

over these 2 numbers:
20215347030006421
21215347030006421
### Impact of this bug
Whenever a duplicate voucher ID is generated from an invoice, Finance staff have to delete the invoice and re-key it into Alma.

**Comment by kevinreiss** [comment]
@mzelesky can you look into the open question you left in the ticket description?

**Comment by mzelesky** [comment]
I was told that we cannot safely ignore the last 6 digits of the voucher ID, so there is just no way to handle all possible numbers. We will stick with the current conversion and handle problems as they arise one at a time.
