### ISSUE TITLE
Remove Tiny TDS Gem

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lib_jobs#444]
We no longer need to connect to SQL Server to process the staff list. 

- [x] Remove dependency from code
- [x] Remove dependencies from CircleCI
- [x] Remove info in ReadME on how to install

**Comment by sandbergja** [comment]
Once this is done, we can also remove the freetds dependencies from the playbook: https://github.com/pulibrary/princeton_ansible/blob/9ed3a4f0ce2e1be3e07f20bb17498c38ebf35bc5/roles/lib_jobs/vars/main.yml#L108-L109
