### ISSUE TITLE
Review POD Workflow

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lib_jobs#480]
- [x] Investigate the current workflow for POD Data Submission- see if triggering a new full dump causes the current code to refresh the entire POD data set in the POD aggregator. 
- [ ] If yes, create a new ticket to look into setting up a separate publishing process for local archiving of POD data on lib-jobs

**Comment by maxkadel** [comment]
Here's what I *think* is happening:
The default behavior is that when you trigger a full POD dump in Alma, the next time the cron job runs (11:30 am UTF / 7:30 am EST), it will pull in any files on lib-sftp that are in /alma/pod that match the pattern `\.tar\.gz$` that are from the last 7 days.

Many of these factors can be changed through environment variables or configuration, but that is the default behavior. 

So yes, any time you trigger a full dump as it is set up now, all those files would be sent to the POD project.
