### ISSUE TITLE
Implement submit collection on new publishing profile.

### ISSUE THREAD

**Issue by christinach** [pulibrary/lib_jobs#495]
### User story
PUL will send updated ReCAP records to SCSB on regular basis. 

### Re-index required?

- [ ] Full re-index
- [ ] Partial re-index
- [x] No re-indexing required

### Implementation notes, if any
Will have a separate publishing job for the ReCAP records in Alma.
The publishing job will not mark suppressed records as deleted. related ticket https://github.com/pulibrary/lib_jobs/issues/498 

Will send a separate record for each item. 

Mermaid chart outlining the workflow: https://github.com/pulibrary/lib_jobs/tree/main/docs/alma_submitcollection

https://gist.github.com/mzelesky/9bd9fa42f102bbadc6b2f8532da6e841

**Comment by christinach** [comment]
per @mzelesky this is a good model to follow https://github.com/pulibrary/lib_jobs/tree/main/app/models/peoplesoft_voucher

**Comment by christinach** [comment]
Work in progress https://github.com/pulibrary/lib_jobs/tree/submit_collection_1

**Comment by kevinreiss** [comment]
@mzelesky @christinach I have a small change to this, after discussion with Ian, Barak, and David Magier out submitCollections updates should be be put i the no_cgd_protection directory in the S3 bucket. They wish any updates to pass through the matching algorithm. Private records are ignored for the purposes of matching.

**Comment by mzelesky** [comment]
This would mean that items that were accessioned into Shared could be changed to Open. Is that desired?

**Comment by mzelesky** [comment]
From https://htcrecap.atlassian.net/wiki/spaces/RTG/pages/2131492869/SCSB+Matching+Algorithm, my understanding is that all updates are run through the matching algorithm, but protecting the CGD just means the CGD won't change based on changed identifiers.
