### ISSUE TITLE
New job to publish Princeton Alma records to SCSB

### ISSUE THREAD

**Issue by christinach** [pulibrary/lib_jobs#496]
New job to publish Princeton Alma records to SCSB

Overview of submit collection:
discussion: https://docs.google.com/document/d/1k5iMH7HCCTUQy8p2E4mk6rRRDNXfiYHCY0e80H8xM0w/edit
mermaid: https://github.com/pulibrary/lib_jobs/tree/main/docs/alma_submitcollection

**Comment by kevinreiss** [comment]
Closing as all sub-issues have been completed.
