### ISSUE TITLE
Update the submit collection script

### ISSUE THREAD

**Issue by christinach** [pulibrary/lib_jobs#500]
Following the recent findings from @mzelesky on the [publishing job exporting records on an item level](https://github.com/pulibrary/lib_jobs/issues/498), @mzelesky will update the script and provide a new gist in this ticket.

**Comment by mzelesky** [comment]
See https://gist.github.com/mzelesky/e6bd007090fae5a492961fcd7dda975e for an updated script that takes advantage of the item-level export.

**Comment by christinach** [comment]
@mzelesky if this is done can you close it? I added it in the current sprint.
