### ISSUE TITLE
AlmaRenew should handle alma timeouts better

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/lib_jobs#513]
### Expected behavior
When alma doesn't renew in a timely fashion to an NCIP renewal request, we should handle it better.

### Actual behavior

We get an alert in honeybadger, but it's not clear whether the renewals actually took place or not (e.g. Alma could have processed the request, just not responded with a status report within the allotted time).

### Steps to replicate

Not sure

### Impact of this bug

Uncertainty about the status of the renewals.

### Honeybadger link and code snippet, if applicable

https://app.honeybadger.io/projects/100710/faults/95947811

```
    def ncip_renew_item(request, http)
      response = http.request request

      if response.is_a? Net::HTTPOK
```

### Implementation notes, if any

- Maybe this could be resolved by some documentation about how to check the status of these renewals.
- The [mermaid diagram](https://github.com/pulibrary/lib_jobs/tree/main/docs/alma_renew) says that NCIP renewal errors should be logged.  Maybe we should do the same for network errors.

**Comment by maxkadel** [comment]
Resolved by #521. Deployed to production 6/26/2023.
