### ISSUE TITLE
Add feature flippers for AlmaFundAdjustment and AlmaInvoiceStatus

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/lib_jobs#514]
This came up while @pmgreen , @mzelesky , @christinach , and I were discussing #512.

### User story

As an alma tech team member, I would like to pause these two jobs at the end of the fiscal year.  The timing may be different between when these jobs need to be on/off, so I would like to be able to pause them separately.

### Urgency

Per @mzelesky, this would be useful to have by June 15.

### Acceptance criteria

- [x] I can successfully turn off the AlmaFundAdjustment job.
- [x] When it is turned off, if the AlmaFundAdjustment rake task is invoked (by cron or manually), it logs a message that it is turned off, and does not continue further.
- [x] I can successfully turn off the AlmaInvoiceStatus job.
- [x] When it is turned off, if the AlmaInvoiceStatus rake task is invoked (by cron or manually), it logs a message that it is turned off, and does not continue further.
- [ ] I can successfully use the feature flippers with Voice Over in Safari.
- [ ] I have checked the feature flippers using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave

### Implementation notes, if any

See #371 for an example.

**Comment by kevinreiss** [comment]
Do this by the next fiscal year close period (June 2024)
