### ISSUE TITLE
authenticate to SVN

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/lib_jobs#516]

**Comment by regineheberlein** [comment]
this gem seems useful for the sendoff to SVN: https://rubygems.org/gems/svn_wc

**Comment by maxkadel** [comment]
@regineheberlein could use collaboration on this one!

**Comment by regineheberlein** [comment]
See https://github.com/pulibrary/princeton_ansible/pull/3971

**Comment by regineheberlein** [comment]
Can we do something similiar to this, just with svn instead of Alma?

```
#configure sendoff to alma
def alma_sftp (filename)
  Net::SFTP.start(ENV['SFTP_HOST'], ENV['SFTP_USERNAME'], { password: ENV['SFTP_PASSWORD'] }) do |sftp|
    sftp.upload!(filename, File.join('/alma/aspace/', File.basename(filename)))
  end
end
```

**Comment by regineheberlein** [comment]
How about just using svn within our Script:
https://stackoverflow.com/questions/3159945/running-command-line-commands-within-ruby-script

**Comment by regineheberlein** [comment]
I can get command-line svn to work using either backticks or ` %x()` with the credentials stored in my keychain. We need to figure out how to do this with an svn working copy on lib_jobs.

**Comment by regineheberlein** [comment]
Currently blocked by pre-commit hook in princeton_ansible

**Comment by regineheberlein** [comment]
blocked by https://github.com/pulibrary/princeton_ansible/issues/4083

**Comment by regineheberlein** [comment]
for future reference, documentation on credentials caching is [at this link](https://svnbook.red-bean.com/en/1.4/svn.serverconfig.netmodel.html#svn.serverconfig.netmodel.credcache).

flags to supply to `svn` are --username and --password

when using ssh+svn, this is helpful (TLDR: keychain is the way go to): https://highlevelbits.com/2007/04/svn-over-ssh-prompts-for-wrong-username.html

**Comment by sandbergja** [comment]
This is done!  Yay!
