### ISSUE TITLE
Add a rescue block around SFTP connections to retry tasks when SSH times out

### ISSUE THREAD

**Issue by rladdusaw** [pulibrary/lib_jobs#517]
### Expected behavior
The scheduled task should complete

### Actual behavior
SFTP connection times out as seen:

https://app.honeybadger.io/projects/100710/faults/96350272
https://app.honeybadger.io/projects/100710/faults/96386513
https://app.honeybadger.io/projects/100710/faults/96427616

### Impact of this bug
E.g. "I can't work until this is fixed" or "I have a workaround"

### Honeybadger link and code snippet, if applicable
https://app.honeybadger.io/projects/100710/faults/96350272

```
Net::SSH::Disconnect: connection closed by remote host
              result = IO.select([self], nil, nil, timeout)
              raise Net::SSH::ConnectionTimeout, "timeout waiting for next packet" unless result
              raise Net::SSH::Disconnect, "connection closed by remote host" if fill <= 0
            end
```

### Implementation notes, if any
~~Similar issues are happening with ASpace, 120s timeout might correct the issue.~~
lib-job deploy user has SSH keep alive value of 120s now. 

Other options:

Adding Rescue/Retry conditions around each to job to retry the effort upon a SSH timeout error. 

Related to https://github.com/pulibrary/princeton_ansible/issues/3961

[Notes on lib-sftp issues](https://docs.google.com/document/d/1JG0PAYiaoYPwxIhISJbXSqo8Lr-oN-HmebHoL0bYhz4/edit#heading=h.3sh3h994o5nn)

**Comment by kevinreiss** [comment]
Increasing the ssh config value to ServerAliveInterval 120 seems to be have potentially addressed this issue.

**Comment by kevinreiss** [comment]
Initially it was set to 30 but several failures were still recorded afterward.

**Comment by christinach** [comment]
see: https://docs.google.com/document/d/1JG0PAYiaoYPwxIhISJbXSqo8Lr-oN-HmebHoL0bYhz4/edit#heading=h.3sh3h994o5nn

**Comment by kevinreiss** [comment]
Let's retry three times upon a failed connection.

**Comment by maxkadel** [comment]
Resolved by https://github.com/pulibrary/lib_jobs/pull/519, deployed to production 6/26/2023
