### ISSUE TITLE
Create requirements for LC call number slips for selectors job

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/lib_jobs#522]
Work together with @pdiskin and @mzelesky on defining the requirements and filling out ticket #234.

**Comment by maxkadel** [comment]
This week Mark and Paul are snowed under with fiscal year end tasks. Scheduled a meeting with them for Wednesday, July 5, 2023

**Comment by maxkadel** [comment]
See [meeting notes](https://docs.google.com/document/d/1NNPszeyBbRin0aJQEMLODcPiUKcdsag2pFcwFcnuTkM/edit)

**Comment by maxkadel** [comment]
Notes put into ticket.
