### ISSUE TITLE
Add Job to Process OCLC Data Sync Exception report

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lib_jobs#553]
## Description 
Alma submits our updates to OCLC for datasync. OCLC takes several hours to process the output this job consumes. Alma will submit this data to OCLC every Tuesday at 7 p.m. This job which will process all exceptions logged by OCLC will than be run at 3 a.m.  Wednesday. OCLC roughly takes 4-6 hours to process this based on past observations. We need to download and process all "exception" files that have been created in the past week. 

- [x] #578
- [x] #579
- [x] #580
- [x] #581
## Implementation Notes
@mzelesky could we have an example file and the code you wrote for this for your current ad hoc process?

**Comment by mzelesky** [comment]
See https://gist.github.com/mzelesky/3e4a0167c00899839fd1d5f79e8bb047

This should be run weekly.
