### ISSUE TITLE
Create Job to Run Alma PulBibNorm as part of OCLC Data Sync

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lib_jobs#554]
The purpose of this job is to move OCLC numbers from the 914 field into the 035 file and remove any existing 035 fields that have an OCLC field. The job is called via Alma's "config" API. 

- [x] Job creates an XML String that will be POSTed to the Config API see this gist https://gist.github.com/mzelesky/2c70e8ad9e41ad66a7c517973eec4cc3. 
- [x] Job then POSTs document to the config API.
- [x] Log 200 response from Alma as success or record non 200 responses as a failure.
- [x] Send email response for failed POSTs to Mark and Peter Green with the reason for failure.
- [x] Schedule task to be run on Thursday morning. 
- [x] If pulibrary/lib_jobs#561 has been completed, update the chart with any changes.

See related ticket pulibrary/princeton_ansible#4075

**Comment by mzelesky** [comment]
I have 3 working scripts for OCLC Data Sync, one of which is to perform a normalization process. It can be run reliably as I have designed the integration to work.

**Comment by mzelesky** [comment]
See https://gist.github.com/mzelesky/2c70e8ad9e41ad66a7c517973eec4cc3

The job does not have to be run in sequence, meaning you don't have to wait for another job to complete before submitting it, though I think running this job the day after the other 2 jobs run would make sense.

**Comment by rladdusaw** [comment]
![Screenshot 2023-07-14 at 9.56.31 AM.png](https://images.zenhubusercontent.com/62a79219df87bc0ebda700f8/996aff93-36de-48f5-bec5-f8ca8cf10a50)
