### ISSUE TITLE
Create Marc Collection with individual Record for Exception MMS ID 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lib_jobs#580]
- [x] Read each exception file and create a new marc collection.
- [x] Add a stub marc record for each MMS ID and add a 001 Field with the MMS ID and a 915 field with the information from the OCLC record about how the MMS ID was processed. 
- [x] Write files to disc, next step moves them to Alma. 

# Implementation Notes
See [gist](https://gist.github.com/mzelesky/3e4a0167c00899839fd1d5f79e8bb047)  for details.
Marc collection files should be limited to 20,000 records. If there are more that were processed we need to create multiple files to be submitted to Alma. (https://gist.github.com/mzelesky/3e4a0167c00899839fd1d5f79e8bb047#file-datasync_error_processing-rb-L52).

**Comment by kevinreiss** [comment]
@mzelesky Is naming the "new" files in this fashion enough for Alma to "know" which files to pick up when it connects to pull these weekly? https://gist.github.com/mzelesky/3e4a0167c00899839fd1d5f79e8bb047#file-datasync_error_processing-rb-L54

**Comment by mzelesky** [comment]
Yes, Alma keeps track of which files have been loaded.
