### ISSUE TITLE
Download Bib Processed Reports via OCLC SFTP

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lib_jobs#583]
- [x] Download bib processed CSV files from OCLC SFTP at /xfer/metacoll/reports. We want to fetch all files with the patter *.BibProcessingReport.txt that have datestamp from the past week. Example file name with a datestamp: PUL-PUL.1012676.IN.BIB.D20230712.T115732756.1012676.pul.non-pcc_27837389230006421_new.mrc_1.BibProcessingReport.txt. Download all files in this pattern from the previous week.  
- [x] Catch any SFTP connection errors and record them in Honeybadger. 

# Implementation Notes
Model for OCLC SFTP https://github.com/pulibrary/lib_jobs/blob/main/app/models/oclc_sftp.rb

Parallel work for exception files: https://github.com/pulibrary/lib_jobs/pull/592

**Comment by rladdusaw** [comment]
Resolved https://github.com/pulibrary/lib_jobs/pull/610
