### ISSUE TITLE
Create stub marc records for each MMS ID in the Bib Processed Report

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lib_jobs#584]
- [x]  Read each Bib processed report file
- [x] Create a new stub marc record for each MMS ID and add a 914 field with the information from the OCLC record about how the MMS ID was processed. See [linked gist ](https://gist.github.com/mzelesky/4382296a6fa4bfac7c68a4139ccbb60e) for details. 
- [x] Write files to disc, next step moves them to Alma. 

# Implementation Notes
See [gist](https://gist.github.com/mzelesky/4382296a6fa4bfac7c68a4139ccbb60e)  for details.
Marc collection files should be limited to 20,000 records. If there are more that were processed we need to create multiple files to be submitted to Alma. https://gist.github.com/mzelesky/4382296a6fa4bfac7c68a4139ccbb60e#file-datasync_xref_processing-rb-L68

See https://github.com/pulibrary/lib_jobs/pull/595 for parallel work on the Exception Files. 

Noting that the 20,000 record limit can be enforced using this new config value added in the completion of ticket #580.

**Comment by kevinreiss** [comment]
@mzelesky Is naming the "new" files in this fashion enough for Alma to "know" which files to pick up when it connects to pull these weekly? https://gist.github.com/mzelesky/3e4a0167c00899839fd1d5f79e8bb047#file-datasync_error_processing-rb-L54

**Comment by mzelesky** [comment]
Yes, Alma keeps track of which files have been loaded.
