### ISSUE TITLE
[send_eads] add rescue to write_eads_to_file

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/lib_jobs#618]
When there is an XML validity error, Nokogiri errors and the method doesn't advance to writing out the file; as a result, the whole process hangs at this iteration. 

Add a rescue that skips the record if Nokogiri can't write to file.

**Comment by regineheberlein** [comment]
In addition, log the error message and the collection ID causing the error.

**Comment by maxkadel** [comment]
@regineheberlein  - can you put the specific error that is being raised by Nokogiri in the ticket?

**Comment by regineheberlein** [comment]
`Nokogiri::XML::SyntaxError: 33:657: FATAL: attributes construct error`

was raised by the missing space in 

`https://library.princeton.edu/special-collections/ask-us'xlink:type='simple'`
