### ISSUE TITLE
Include Ineligible Alma Users in Alma Daily Patron Feed Processing

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lib_jobs#659]
### User story
When a user moves to an ineligible state in the Alma patron file, Alma should recognize this and update their account accordingly. 

### Concrete example
A staff member leaves the library. After their last day of employment they will appear as ineligible.

See [current documentation for this process](https://github.com/pulibrary/lib_jobs/tree/main/docs/alma_people)

### Acceptance criteria

- [x] Create a second API call to the OIT service to request all users who moved to an ineligible state in the last 24 hours. See https://github.com/pulibrary/lib_jobs/blob/96f5ff082a508f26329b7640c9f787ea68733487/docs/alma_people/README.md. 
- [x] Create a new daily file in the /people directory that contains those newly ineligible users. 
- [x] The file name form can include _I to indicate it's comprised of ineligible patrons. 
- [x] Confirm with Alma team that Alma is configured to rotate the file daily using the .processed convention on the lib-sftp server environment. 
- [x] Users are expired on the day they reach that state, per Joan we do not need a grace period. 
- [x] Send the file to only the staging environment initially. 
- [x] Use the flipflop Gem, there will be a period of testing with Alma Sandbox before this can be put into production so we'll want to toggle it off in prod and on in staging. 

### Implementation Notes
The Alma Integration that consumes this data is the [Student Information System](https://knowledge.exlibrisgroup.com/Alma/Product_Documentation/010Alma_Online_Help_(English)/090Integrations_with_External_Systems/050User_Management/010Student_Information_Systems). The <status> XML element is what Alma looks at to decide if a user active, see https://github.com/pulibrary/lib_jobs/blob/96f5ff082a508f26329b7640c9f787ea68733487/app/models/alma_people/alma_xml_person.rb#L43.

**Comment by mzelesky** [comment]
Waiting on input from Joan on if the user should get a grace period before their account expires.

**Comment by mzelesky** [comment]
From Joan:

> Hi,
> I’ve thought about the date to use once patrons have “left”.  Let’s use a grace period of 1 week.  I may change it in the future but it seems less risky at this point.
>  
> I’m wondering how retirees will be affected, if at all.
>  
> I’m also hoping that patrons who are here on term appointments and then renewed will be handled appropriately. People soft may show that they were Terminated on a date and then Active on that same date.
>

**Comment by kevinreiss** [comment]
After further discussion Joan decided we don't need a grace period. Users should be expired on the date they move that state.

**Comment by mzelesky** [comment]
The next step is to start loading ineligible users into the Sandbox.
