### ISSUE TITLE
Match records based on keywords

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/lib_jobs#678]
### User story
A number of selectors would like to be able to match records not only on keywords in subject fields, but also in other fields, and allow use of wildcards. 

### Concrete example

> I very much would need a general keyword search, since as usual area studies (as well as period studies) are difficult to catch otherwise.
> The products we have in the past always could set a range of keywords such as chin*, japan* etc, in title and notes, not just 6xx; and that’s how we get slips from elsewhere as well.

### Acceptance criteria
- [ ] Selectors can provide a list of keywords to match in fields other than subject fields, and return matching monographs in the CSV
- [ ] Selectors can provide keywords with wildcards and return matching monographs in the CSV

### Implementation notes, if any
- It is possible this would require indexing fields in order to make it performant / scalable, which would be a big change.

**Comment by mzelesky** [comment]
From the feedback from Martin quoted above, I take it to mean the following fields:
1XX
2XX
5XX
7XX
8XX

Can you say more about requiring indexing of fields to make it performant? It sounds like that would be a lot of overhead vs. letting ruby-marc iterate through the fields.
