### ISSUE TITLE
Create AlmaBrowzine Job

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/lib_jobs#69]
Produce the data normally sent to GoogleScholar and send it along to Browzine

Can we hack into here to get alma to create the file for us? https://knowledge.exlibrisgroup.com/Alma/Product_Documentation/010Alma_Online_Help_(English)/090Integrations_with_External_Systems/030Resource_Management/150Publishing_Electronic_Holdings_to_Google_Scholar

The current script copies the Google Scholar XML for the current time period to a static URL that the vendor downloads it from. If the built-in integration still produces a file that lives at a static place that can be downloaded in some fashion we can keep using it.

**Comment by kevinreiss** [comment]
@pmgreen I think there is an actual dedicated alma job for this function, correct?

**Comment by pmgreen** [comment]
@kevinreiss yes, and it's been tested successfully

**Comment by kevinreiss** [comment]
Ok, closing this one. Thx.
