### ISSUE TITLE
Create New Web Staff Report from Airtable Data

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lib_jobs#697]
- [x] Implement Connection to Airtable to pick up "PUL Staff Directory Report". This read-only report provides additional data about each employee. Use the staff member's email address as the overlay point to add the following additional data fields to their row in the output CSV. 
- [x] PUID (i.e. the employee ID)
- [x] NetID
- [x] Phone - Use airtable University Phone
- [x] Name - Use PULPreferred Name
- [x] lastName
- [x] firstName
- [x] email
- [x] Address
- [x] Building from pul:Building field
- [x] Department - from the Division field 
- [x] Add "Division" Field from pul:Deparment field
- [x] Add "Unit" Field from pul:Unit field
- [x] Add "Team" Field from pul:Team field
- [x] Add "Areas of Study Field" - from pul:Areas of Study this will be a delimited list of value use a "//" value to delimit.
- [ ] New public URL can be https://lib-jobs.princeton.edu/pul-staff-report.csv

## Implementation Notes
[Current Process](https://github.com/pulibrary/lib_jobs/tree/main/docs/web_staff) (for reference)
[Airtable URL](https://airtable.com/appv7XA5FWS7DG9oe/tblM0iymGN5oqDUVm/viwHf9IPWSnVpidzL?blocks=hide)
[API docs for Library Staff Airtable](https://airtable.com/appv7XA5FWS7DG9oe/api/docs)
[Auth docs for Airtable](https://airtable.com/developers/web/api/authentication) (personal access tokens are ok for testing, we likely want to choose OAUTH for any processes that run on our servers. 
A known unique Identifier (net ID or employee ID) should be added to the airtable to ensure a reliable overlay. 

## Logging In to Airtable Backend
Visit [https://airtable.com/login](https://airtable.com/login), select "Sign in with Single Sign On". Give your email with "@princeton.edu" the first time you login an access request will be sent to Jon to approve your access to the data.

**Comment by kevinreiss** [comment]
The net ID and pu ID values are now in Airtable.

**Comment by kevinreiss** [comment]
Right now the process is asking the automation to fill in a Captcha. Oauth seems really set-up to be used if you are using Airtable to provide a web application. Will pivot to seeing if we can use a personal access token with a service account to interact with airtable in an automated way.

**Comment by sandbergja** [comment]
Airtable's documentation says that the image links provided by the API may expire after 2 hours.  They recommend downloading them.  Where should we host those downloaded images?  Lib-jobs?
