### ISSUE TITLE
[Newly Cataloged for Selectors] Make publication locations configurable

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/lib_jobs#703]
### User story
Depending on selection area, coverage of US, UK, and Canada publications varies widely. 

For some selectors, it is more helpful to exclude these publication locations in order to avoid duplication with other selection services, and for others it is more helpful to include them, since other services do not cover their selection area as well.

In order to include these publications for some selectors and not others, we should make this configurable.

### Concrete example
The selector for Judaic Studies and Hebrew has indicated that these titles are not as well covered by existing services (YBP / Gobi), including the ones published in the US, UK, and Canada, so he would like to be able to include these titles in his weekly CSV. 

### Acceptance criteria
- [x] Double check with existing selectors whether they wish to continue excluding these publication locations
- [x] For selectors still wishing to exclude these publication locations, they are excluded from their CSV
- [x] For selectors wishing to include these publication locations, they are included in their CSV

### Implementation notes, if any
- This will require changes to the [relevant_to_selector?](https://github.com/pulibrary/lib_jobs/blob/51dd8d95ad0f6dcdbdbc193922c3c523b7aa7c83/app/models/oclc/record.rb#L15-L17) and [generally_relevant?](https://github.com/pulibrary/lib_jobs/blob/51dd8d95ad0f6dcdbdbc193922c3c523b7aa7c83/app/models/oclc/record.rb#L11-L13) methods, as well as the configuration file

**Comment by maxkadel** [comment]
@mzelesky  - selectors can now decide whether to exclude or include US, UK, and Canada publications. It defaults to excluding publications from those locations. You may want to update any documentation on your end with this change.

**Comment by mzelesky** [comment]
That's great! I'll make sure we document that possibility.
