### ISSUE TITLE
Locations and Container Profiles not all appearing in dropdown

### ISSUE THREAD

**Issue by kelynch** [pulibrary/lib_jobs#74]
This is dependent on fixing Sidekiq and caching consistently.

**Comment by jrgriffiniii** [comment]
I am not certain if this is the case any longer, but this might just be related to the need to update the caching on occasion.

**Comment by jrgriffiniii** [comment]
I suspect that this may no longer be valid, as this was likely related to some ActiveRecord caching which was removed. Please see:
- https://github.com/pulibrary/lib_jobs/pull/133
- https://github.com/pulibrary/lib_jobs/pull/132
