### ISSUE TITLE
AbIDs need to generate uniquely

### ISSUE THREAD

**Issue by kelynch** [pulibrary/lib_jobs#75]
Currently abIDs are unique per batch but not across the board.

**Comment by jrgriffiniii** [comment]
This was addressed in https://github.com/pulibrary/lib_jobs/pull/98, but given the other refactoring changes, I can understand a proposal to just open this as a smaller-scale bug-fix.

**Comment by jrgriffiniii** [comment]
Depending upon the response to #115, this may no longer be necessary.
