### ISSUE TITLE
Container Profiles and Locations should sync to ASpace TopContainer records

### ISSUE THREAD

**Issue by kelynch** [pulibrary/lib_jobs#76]
Add parameters for container profiles and locations to sync to ASpace

**Comment by jrgriffiniii** [comment]
Currently the synchronization is between AbsoluteId Models and ArchivesSpace resources just links between the `indicator` and `barcode` fields of TopContainer records:

![image](https://user-images.githubusercontent.com/1443986/111191429-703f9f00-858e-11eb-81bc-a3271b6603b8.png)

There should also be links between Container Profiles and Locations for TopContainer records.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/lib_jobs/compare/absolute-ids-validate-duplicate...absolute-ids-sync-profiles-locations mostly resolves this, but other refactoring should be given a higher priority.

**Comment by tpendragon** [comment]
@jrgriffiniii This is done right?
