### ISSUE TITLE
Ignore Empty Rows in Airtable CSV

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lib_jobs#805]
The airtable export can contain empty rows if a data entry has been made within airtable. The airtable exporter should just ignore these rows. 

- The original airtable (which may or may not contain empty rows) is at https://airtable.com/appv7XA5FWS7DG9oe/tblM0iymGN5oqDUVm/viwHf9IPWSnVpidzL?blocks=hide
- The CSV that we create from this airtable (which we don't want to have any empty rows, even if the original airtable did) can be found at http://lib-jobs-staging.princeton.edu/pul-staff-report.csv

## Current State
Right now the airtable contains an empty row. Currently that becomes an empty row in our CSV export.

**Comment by sandbergja** [comment]
Here is an example of the CSV file we generated with empty rows, back when the airtable also had empty rows.
[pul-staff-report.csv](https://github.com/user-attachments/files/16550521/pul-staff-report.csv)
