### ISSUE TITLE
[airtable staff directory] Use field IDs, rather than field names, to get data from airtable API

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/lib_jobs#806]
### What maintenance needs to be done?

Use field IDs, rather than field names, to get data from airtable API

### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### Why is this maintenance needed?
From the Airtable API docs:

> We recommend using field ids over field names where possible, to reduce modifications to your API request if the user changes the field name later.

### Acceptance criteria
 - [ ] We use field IDs, rather than field names, to get data from airtable API

### Implementation notes, if any
* The IDs can be found in the [airtable staff directory documentation](https://airtable.com/appv7XA5FWS7DG9oe/api/docs)

**Comment by maxkadel** [comment]
Done, deployed to production
