### ISSUE TITLE
Add New Fields to Airtable CSV Export

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lib_jobs#815]
### What maintenance needs to be done?
The [airtable CSV feed](https://lib-jobs.princeton.edu/pul-staff-report.csv ) should explose several new fields that can be leveraged for Discovery

### Level of urgency
- [x] High
- [ ] Moderate
- [ ] Low

### Why is this maintenance needed?
Additional data that can enhance staff discovery is available. 

### Acceptance criteria
 - [x] ~Add 'Area of Study' field. This row can contain multiple values separated by //.~
 - [x] Add "Other Entities" field. This can contain multiple values separated by //.  https://github.com/pulibrary/lib_jobs/pull/817
 - [x] ~Add the "my scheduler" field. This will be a URL when present.~
 - [ ] Section is now labeled as "team" in the Airtable data. We should swap the column names. Field should be keyword searchable.

**Comment by sandbergja** [comment]
@kevinreiss : we looked today, and both Airtable and lib_jobs only have a "team" field, we couldn't find anything referencing "section".  Is there anything else we need to do for that checkbox?
